travel = ['universal', 'disney', 'tokyo', 'rio', 'chengdu']
print(travel)
sorted(travel)
print(travel)
sorted(travel,reverse=True)
print(travel)
travel.reverse()
print(travel)
travel.reverse()
print(travel)
travel.sort()
print(travel)
travel.sort(reverse=True)
print(travel)